In [1]:
#import pandas

In [2]:
import pandas as pd # import pandas เป็น pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import os

path = '/content/drive/MyDrive/Basic Program'

In [5]:
covid_file_path = os.path.join(path,'confirmed-cases.csv')
print(covid_file_path)

/content/drive/MyDrive/Basic Program/confirmed-cases.csv

In [6]:
a = path + 'confirmed-cases.csv'
print(a)

/content/drive/MyDrive/Basic Programconfirmed-cases.csv

## load data to memory

In [7]:
import pandas

In [8]:
data_covid = pd.read_csv(covid_file_path)
data_covid

/tmp/ipykernel_4492/318669438.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_covid = pd.read_csv(covid_file_path)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
...,...,...,...,...,...,...,...,...,...,...,...
839766,839767,12/8/2021,11/8/2021,ชาย,52.0,ปี,NaN,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839767,839768,12/8/2021,11/8/2021,ชาย,34.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839768,839769,12/8/2021,11/8/2021,ชาย,31.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839769,839770,12/8/2021,11/8/2021,ชาย,83.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839770,839771,12/8/2021,11/8/2021,ชาย,47.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN

In [9]:
data_covid.head()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

In [10]:
data_covid.shape

(839771, 11)

## ชี้ค่าในตาราง

#### basic

In [ ]:
data_covid['province_of_onset'] # ข้อมูลในคอลัมน์นี้มีอะไรบ้าง

0         กรุงเทพมหานคร
1         กรุงเทพมหานคร
2                นครปฐม
3         กรุงเทพมหานคร
4         กรุงเทพมหานคร
              ...
839766        กาญจนบุรี
839767        กาญจนบุรี
839768        กาญจนบุรี
839769        กาญจนบุรี
839770        กาญจนบุรี
Name: province_of_onset, Length: 839771, dtype: object

In [ ]:
data_covid['province_of_onset'][4] # อยากชี้ไปที่ข้อมูลตัวนั้นเลยก็ ชี้ไปที่ index นั้นๆ เลย

'กรุงเทพมหานคร'

#### .iloc

In [ ]:
data_covid.iloc[4,7] # แปลงการมองตารางเป็นแบบ array เป็นการบอกว่าอยู่แถวที่เท่าไหรหลักที่เท่าไหร่

'นนทบุรี'

## Table slicing

#### ตัดมาเฉพาะ column ที่ต้องการ

In [11]:
#อยากรู้เฉพราะคอลัมน์ที่ต้องการ
smaller_table = data_covid[['announce_date','province_of_onset','risk']]
smaller_table

       announce_date province_of_onset                              risk
0          12/1/2020     กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
1          17/1/2020     กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
2          22/1/2020            นครปฐม  คนต่างชาติเดินทางมาจากต่างประเทศ
3          22/1/2020     กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
4          24/1/2020     กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
...              ...               ...                               ...
839766     12/8/2021         กาญจนบุรี                  ทัณฑสถาน/เรือนจำ
839767     12/8/2021         กาญจนบุรี                  ทัณฑสถาน/เรือนจำ
839768     12/8/2021         กาญจนบุรี                  ทัณฑสถาน/เรือนจำ
839769     12/8/2021         กาญจนบุรี                  ทัณฑสถาน/เรือนจำ
839770     12/8/2021         กาญจนบุรี                  ทัณฑสถาน/เรือนจำ

[839771 rows x 3 columns]

#### ตัดเฉพาะ rows ที่ต้องการ ทำได้หลายแบบ

##### แบบง่าย แต่ใช้การอะไรไม่ค่อยจะได้ (มองเป็น array แล้วตัดแบบ array)

In [12]:
data_covid.iloc[1:5,:] #เอาตั้งแต่ row 1 ถึงแถวที่ 4

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

แบบ advanced แต่ใช้ประโยชน์ได้เยอะกว่า (ตัดแบบใช้ logic query) เรื่องหลักเลย

In [13]:
Data_a = data_covid.iloc[:5,:]
Data_a

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

In [14]:
Data_a[[True,False,False,True,False]] #กรอง data ได้ว่าเร้าต้องการหรือไม่ต้องการ row ไหน แลพ list of logics ต้องมีความยาวเท่ากับจำนวน row ของตาราง pandas

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

In [15]:
data_covid[data_covid['province_of_onset']=='ขอนแก่น']

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
181,182,18/3/2020,15/3/2020,ชาย,33.0,ปี,Thailand,ขอนแก่น,สนามมวย,ขอนแก่น,เมือง
463,464,22/3/2020,21/3/2020,หญิง,36.0,ปี,Thailand,ขอนแก่น,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ขอนแก่น,เมือง
1467,1468,30/3/2020,26/3/2020,ชาย,19.0,ปี,Thailand,ขอนแก่น,คนไทยเดินทางกลับจากต่างประเทศ,ขอนแก่น,เมือง
1971,1972,3/4/2020,31/3/2020,หญิง,70.0,ปี,Thailand,ขอนแก่น,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ขอนแก่น,เมือง
2638,2639,15/4/2020,14/4/2020,หญิง,63.0,ปี,Thailand,ขอนแก่น,สัมผัสผู้เดินทางจากต่างประเทศ,ขอนแก่น,น้ำพอง
...,...,...,...,...,...,...,...,...,...,...,...
839669,839670,12/8/2021,11/8/2021,ชาย,46.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN
839670,839671,12/8/2021,11/8/2021,ชาย,58.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN
839671,839672,12/8/2021,11/8/2021,ชาย,30.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN
839672,839673,12/8/2021,11/8/2021,ชาย,20.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN
839673,839674,12/8/2021,11/8/2021,ชาย,20.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN

In [16]:
data_covid['province_of_onset']=='ขอนแก่น'

0         False
1         False
2         False
3         False
4         False
          ...
839766    False
839767    False
839768    False
839769    False
839770    False
Name: province_of_onset, Length: 839771, dtype: bool

In [ ]:
data_covid[data_covid['province_of_onset']=='ขอนแก่น'] # ตัดมเฉพาะแถวที่เป็นจังหวัดขอนแก่น

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
181,182,18/3/2020,15/3/2020,ชาย,33.0,ปี,Thailand,ขอนแก่น,สนามมวย,ขอนแก่น,เมือง
463,464,22/3/2020,21/3/2020,หญิง,36.0,ปี,Thailand,ขอนแก่น,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ขอนแก่น,เมือง
1467,1468,30/3/2020,26/3/2020,ชาย,19.0,ปี,Thailand,ขอนแก่น,คนไทยเดินทางกลับจากต่างประเทศ,ขอนแก่น,เมือง
1971,1972,3/4/2020,31/3/2020,หญิง,70.0,ปี,Thailand,ขอนแก่น,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ขอนแก่น,เมือง
2638,2639,15/4/2020,14/4/2020,หญิง,63.0,ปี,Thailand,ขอนแก่น,สัมผัสผู้เดินทางจากต่างประเทศ,ขอนแก่น,น้ำพอง
...,...,...,...,...,...,...,...,...,...,...,...
839669,839670,12/8/2021,11/8/2021,ชาย,46.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN
839670,839671,12/8/2021,11/8/2021,ชาย,58.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN
839671,839672,12/8/2021,11/8/2021,ชาย,30.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN
839672,839673,12/8/2021,11/8/2021,ชาย,20.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN
839673,839674,12/8/2021,11/8/2021,ชาย,20.0,ปี,Thailand,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ขอนแก่น,NaN

การชี้ค่าในตารางด้วย data_covid[***x***] ค่า ***x*** สามารถมีค่าที่ใส่เข้าไปได้ 2 แบบ


1.   ชื่อ column
2.   ใส่ rows ที่ต้องการ (ใส่ list ที่มี***ขนาดเท่ากับจำนวนแถว*** แล้วบอกว่าเอา แถวไหนบ้างโดยใช้ logical expression (```True```/```False```))

In [17]:
eight_rows_covid = data_covid.iloc[:8,:] # ตารางตัวอย่าง
eight_rows_covid

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
5,6,25/1/2020,NaN,หญิง,33.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
6,7,26/1/2020,NaN,หญิง,57.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
7,8,26/1/2020,NaN,หญิง,73.0,ปี,China,ประจวบคีรีขันธ์,คนต่างชาติเดินทางมาจากต่างประเทศ,ประจวบคีรีขันธ์,หัวหิน

In [18]:
eight_rows_covid[[True,False,True,True,False,True,False,False]]   #2.   ใส่ rows ที่ต้องการ

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
5,6,25/1/2020,NaN,หญิง,33.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

In [19]:
# ตาราง eight_rows_covid ให้เข้าไปดูที่คอลัมน์ province_of_onset ว่าเท่ากับ กรุงเทพมหานครมั้ย
eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร'  #สร้าง list ของ logical expression

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: province_of_onset, dtype: bool

In [20]:
# ตัดมาเฉพาะอันที่เราต้องการก็คือกรุงเทพ
eight_rows_covid[eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร']  #เราเอา 2 บรรทัดบนมาบวกกัน

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
5,6,25/1/2020,NaN,หญิง,33.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
6,7,26/1/2020,NaN,หญิง,57.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

HW (ให้ใช้เฉพาะที่อาจารย์สอนไปแล้วในวิชานี้)

1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด
2.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

3. หาจำนวนผู้ป่วยที่เป็นคน "**คนต่างชาติเดินทางมาจากต่างประเทศ**"

In [21]:
this_data = data_covid[['sex','age','province_of_onset']]

In [22]:
this_data

         sex   age province_of_onset
0       หญิง  61.0     กรุงเทพมหานคร
1       หญิง  74.0     กรุงเทพมหานคร
2       หญิง  73.0            นครปฐม
3        ชาย  68.0     กรุงเทพมหานคร
4       หญิง  66.0     กรุงเทพมหานคร
...      ...   ...               ...
839766   ชาย  52.0         กาญจนบุรี
839767   ชาย  34.0         กาญจนบุรี
839768   ชาย  31.0         กาญจนบุรี
839769   ชาย  83.0         กาญจนบุรี
839770   ชาย  47.0         กาญจนบุรี

[839771 rows x 3 columns]

In [23]:
# อาจาร์ยพาทำ
female = this_data[this_data['sex']=='หญิง']
female.describe()

           sex       age province_of_onset
count   399881  377228.0            365621
unique       1     228.0               145
top       หญิง      25.0     กรุงเทพมหานคร
freq    399881    9744.0             89218

In [24]:
female = this_data[this_data['sex']=='หญิง'] # แยกเป็นผู็หญิง
female['age'] # เลือกมาแค่อายุ

0         61.0
1         74.0
2         73.0
4         66.0
5         33.0
          ...
839737    57.0
839738    50.0
839739    37.0
839740    24.0
839741    26.0
Name: age, Length: 399881, dtype: object

In [25]:
female['age'] = pd.to_numeric(female['age'],errors='coerce')
sum = 0
N = 0
for a in female['age']:

    if pd.notna(a) and a > 0: # เช็กว่าไม่ใช่ NaN และมากว่า 0
        sum += a # sum = sum + a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง {sum/N}')

/tmp/ipykernel_4492/752304539.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  female['age'] = pd.to_numeric(female['age'],errors='coerce')

อายุเฉลี่ย ของ ผู้ป่วยหญิง 36.16090881617699

In [26]:
female_KK = female[female['province_of_onset']=='ขอนแก่น']

sum = 0
N = 0
for a in female_KK['age']:

    if a > 0:
        sum += a # sum = sum + a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น {sum/N}')

อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น 34.59362745098039

การจัดการ Missing Value

- ลบ record ที่เป็น missing
- แทนที่ ค่า missing ด้วยค่าที่เหมาะสม mean, default, category-unknown
- ใช้ ค่าจาก columns อื่นๆ ช่วยประมาณค่า ค่าใน column ที่หายไป (regression, deep learning, etc.)

### ลบ record (dropna)
อันนี้วิธีง่ายที่สุด อันไหนเป็น missing ก็ drop ออกไปเลย

missing = ```None``` ```NA```(not autorized) ```NaN``` (not a number)

In [27]:
this_data.shape #(12423, 3)

(839771, 3)

In [28]:
print(data_covid.shape)
print(data_covid.dropna().shape) # ดู missing ทุกคอลัมน์เลย

(839771, 11)
(599988, 11)

In [29]:
this_data.dropna().shape

(674906, 3)

In [30]:
this_data.dropna()

         sex   age province_of_onset
0       หญิง  61.0     กรุงเทพมหานคร
1       หญิง  74.0     กรุงเทพมหานคร
2       หญิง  73.0            นครปฐม
3        ชาย  68.0     กรุงเทพมหานคร
4       หญิง  66.0     กรุงเทพมหานคร
...      ...   ...               ...
839766   ชาย  52.0         กาญจนบุรี
839767   ชาย  34.0         กาญจนบุรี
839768   ชาย  31.0         กาญจนบุรี
839769   ชาย  83.0         กาญจนบุรี
839770   ชาย  47.0         กาญจนบุรี

[674906 rows x 3 columns]

In [31]:
this_data.dropna()
print(this_data.shape)

(839771, 3)

In [ ]:
this_data.dropna(inplace=True)

/tmp/ipykernel_1013/3935554116.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  this_data.dropna(inplace=True)

In [ ]:
this_data.dropna(inplace=True) # อัพเดทค่าในตารางเข้าไปแก้ไขเลย
print(this_data.shape)

(674906, 3)

/tmp/ipykernel_1013/2740560424.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  this_data.dropna(inplace=True) # อัพเดทค่าในตารางเข้าไปแก้ไขเลย

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]
this_data.shape

(839771, 3)

In [ ]:
this_data.dropna().shape #ตัดค่า missing ออก

(674906, 3)

In [ ]:
this_data.dropna(subset=['age']).shape # ให้มันไปดูที่คอลัมน์ age

(763606, 3)

### แทน missing ด้วยค่าที่เหมาะสม (```fillna```)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
this_data.head()

    sex   age province_of_onset
0  หญิง  61.0     กรุงเทพมหานคร
1  หญิง  74.0     กรุงเทพมหานคร
2  หญิง  73.0            นครปฐม
3   ชาย  68.0     กรุงเทพมหานคร
4  หญิง  66.0     กรุงเทพมหานคร

In [ ]:
print(f'จำนวน record ก่อน drop missing ใน province {this_data.shape[0]}')
print(f'จำนวน record หลัง drop missing ใน province {this_data.dropna(subset=["province_of_onset"]).shape[0]}')

จำนวน record ก่อน drop missing ใน province 839771
จำนวน record หลัง drop missing ใน province 740737

In [ ]:
# กรณีที่เราไม่มีค่าแล้วเราไม่สามารถเดาได้ เราก็สร้างจังหวัดใหม่ขึ้นมาเลย
this_data_updated = this_data.fillna(value={'sex':'ไม่รู้', 'age':-1, 'province_of_onset':'ไม่รู้'})
this_data_updated.head()

# ถ้าตรง value เราใส่แค่ค่าเดียวมันก็จะเติมตรง na ทุกๆคอลัมน์์เลย
# แต่ถ้าเราใส่เป็น dict เราก็จะสามารถระบุได้เหมือนกับตัวอย่างข้อนี้เลย

    sex   age province_of_onset
0  หญิง  61.0     กรุงเทพมหานคร
1  หญิง  74.0     กรุงเทพมหานคร
2  หญิง  73.0            นครปฐม
3   ชาย  68.0     กรุงเทพมหานคร
4  หญิง  66.0     กรุงเทพมหานคร

In [ ]:
this_data_updated[this_data_updated['sex']=='ไม่รู้']

           sex   age province_of_onset
4397    ไม่รู้    -1         สมุทรสาคร
4398    ไม่รู้    -1         สมุทรสาคร
4399    ไม่รู้    -1         สมุทรสาคร
4400    ไม่รู้    -1         สมุทรสาคร
4401    ไม่รู้    -1         สมุทรสาคร
...        ...   ...               ...
838332  ไม่รู้   3.0     กรุงเทพมหานคร
839174  ไม่รู้  47.0     กรุงเทพมหานคร
839304  ไม่รู้    -1            ไม่รู้
839396  ไม่รู้    -1        นครราชสีมา
839397  ไม่รู้    -1        นครราชสีมา

[54895 rows x 3 columns]

In [ ]:
# ถ้าบรรทัดไหนมีคำว่าไม่รู้ มันจะขึ้น true
this_data_updated['province_of_onset']=='ไม่รู้'

0         False
1         False
2         False
3         False
4         False
          ...
839766    False
839767    False
839768    False
839769    False
839770    False
Name: province_of_onset, Length: 839771, dtype: bool

In [ ]:
# สามารถทำได้เพราะเพราะการชี้ค่าในตารางมี list ที่มีขนาดเท่ากับจำนวนแถว ก็คือdatacovid กับ disdataupdate จำนวนแถวเท่ากัน
data_covid[this_data_updated['province_of_onset']=='ไม่รู้']

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
415,416,22/3/2020,22/3/2020,ชาย,29.0,ปี,Thailand,กรุงเทพมหานคร,สนามมวย,NaN,NaN
530,531,22/3/2020,20/3/2020,ชาย,37.0,ปี,Thailand,กรุงเทพมหานคร,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,NaN,NaN
556,557,22/3/2020,21/3/2020,หญิง,6.0,ปี,Thailand,กรุงเทพมหานคร,สนามมวย,NaN,NaN
577,578,22/3/2020,20/3/2020,ชาย,NaN,NaN,Thailand,กรุงเทพมหานคร,สนามมวย,NaN,NaN
589,590,22/3/2020,21/3/2020,ชาย,NaN,NaN,Thailand,กรุงเทพมหานคร,อยู่ระหว่างการสอบสวน,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
838196,838197,12/8/2021,11/8/2021,NaN,36.0,ปี,NaN,กรุงเทพมหานคร,ระบุไม่ได้,NaN,NaN
838371,838372,12/8/2021,11/8/2021,ชาย,28.0,ปี,Cambodian,กรุงเทพมหานคร,อื่นๆ,NaN,NaN
838395,838396,12/8/2021,11/8/2021,ชาย,45.0,ปี,Cambodian,กรุงเทพมหานคร,ระบุไม่ได้,NaN,NaN
839144,839145,12/8/2021,11/8/2021,ชาย,76.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,NaN,NaN
839304,839305,12/8/2021,11/8/2021,NaN,NaN,NaN,NaN,กรุงเทพมหานคร,ระบุไม่ได้,NaN,NaN

In [ ]:
this_data_updated_2 = this_data.fillna(value={'province_of_onset':'ไม่รู้'})

In [ ]:
this_data_updated_2[this_data_updated['sex']=='ไม่รู้']

        sex   age province_of_onset
4397    NaN   NaN         สมุทรสาคร
4398    NaN   NaN         สมุทรสาคร
4399    NaN   NaN         สมุทรสาคร
4400    NaN   NaN         สมุทรสาคร
4401    NaN   NaN         สมุทรสาคร
...     ...   ...               ...
838332  NaN   3.0     กรุงเทพมหานคร
839174  NaN  47.0     กรุงเทพมหานคร
839304  NaN   NaN            ไม่รู้
839396  NaN   NaN        นครราชสีมา
839397  NaN   NaN        นครราชสีมา

[54895 rows x 3 columns]

### การวนลูป record ในตาราง  (```.iterrows```)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
for each_row in this_data.iterrows(): # ตัว iterrows มันใช้ในการวนลูกเข้าไปในแต่ละเรคคอร์ดของแต่ละตารางได้
    # print(each_row)
    # print(each_row[1]) # ชี้ Indict 1
    if (each_row[1]['age'] == 20) and (each_row[1]['province_of_onset'] == 'ขอนแก่น'):
        print(each_row)
# ผลการ print ออกมามันเรียกว่าทัฟเฟิล หรือก็คล้ายๆกับ list วงเล็บวงกลม

(9335, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 9335, dtype: object)
(31050, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 31050, dtype: object)
(34968, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 34968, dtype: object)
(36072, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 36072, dtype: object)
(39418, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 39418, dtype: object)
(42498, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 42498, dtype: object)
(44230, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 44230, dtype: object)
(45587, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 45587, dtype: object)
(48523, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 48523, dtype: object)
(53609, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 53609, dtype: object)
(57679, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 57679, dtype: object)
(59921, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 59921, dtype: object)
(59930, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 59930, dtype: object)
(62012, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 62012, dtype: object)
(194272, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 194272, dtype: object)
(256640, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 256640, dtype: object)
(267358, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 267358, dtype: object)
(267368, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 267368, dtype: object)
(304435, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 304435, dtype: object)
(312286, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 312286, dtype: object)
(321955, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 321955, dtype: object)
(321996, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 321996, dtype: object)
(340650, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 340650, dtype: object)
(340671, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 340671, dtype: object)
(349134, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 349134, dtype: object)
(368051, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 368051, dtype: object)
(377063, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 377063, dtype: object)
(377130, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 377130, dtype: object)
(388236, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 388236, dtype: object)
(401881, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 401881, dtype: object)
(410329, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 410329, dtype: object)
(410353, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 410353, dtype: object)
(410396, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 410396, dtype: object)
(420924, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 420924, dtype: object)
(433189, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 433189, dtype: object)
(433192, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 433192, dtype: object)
(433214, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 433214, dtype: object)
(433256, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 433256, dtype: object)
(433269, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 433269, dtype: object)
(433293, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 433293, dtype: object)
(446755, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 446755, dtype: object)
(452846, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 452846, dtype: object)
(452894, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 452894, dtype: object)
(460492, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 460492, dtype: object)
(460543, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 460543, dtype: object)
(460590, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 460590, dtype: object)
(466802, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 466802, dtype: object)
(466810, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 466810, dtype: object)
(466875, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 466875, dtype: object)
(475443, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 475443, dtype: object)
(475498, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 475498, dtype: object)
(475501, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 475501, dtype: object)
(481816, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 481816, dtype: object)
(481818, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 481818, dtype: object)
(481824, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 481824, dtype: object)
(496736, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 496736, dtype: object)
(496745, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 496745, dtype: object)
(496947, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 496947, dtype: object)
(505641, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 505641, dtype: object)
(520750, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 520750, dtype: object)
(535484, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 535484, dtype: object)
(553001, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 553001, dtype: object)
(553135, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 553135, dtype: object)
(553150, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 553150, dtype: object)
(555059, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 555059, dtype: object)
(560192, sex                      NaN
age                     20.0
province_of_onset    ขอนแก่น
Name: 560192, dtype: object)
(570704, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 570704, dtype: object)
(570785, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 570785, dtype: object)
(570796, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 570796, dtype: object)
(588443, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 588443, dtype: object)
(588445, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 588445, dtype: object)
(588447, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 588447, dtype: object)
(588468, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 588468, dtype: object)
(588525, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 588525, dtype: object)
(588532, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 588532, dtype: object)
(607922, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 607922, dtype: object)
(607942, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 607942, dtype: object)
(620478, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 620478, dtype: object)
(625602, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 625602, dtype: object)
(625628, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 625628, dtype: object)
(625651, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 625651, dtype: object)
(625717, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 625717, dtype: object)
(643471, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 643471, dtype: object)
(643473, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 643473, dtype: object)
(643528, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 643528, dtype: object)
(643600, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 643600, dtype: object)
(663475, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 663475, dtype: object)
(663521, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 663521, dtype: object)
(663570, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 663570, dtype: object)
(663591, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 663591, dtype: object)
(683820, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 683820, dtype: object)
(704781, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 704781, dtype: object)
(704805, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 704805, dtype: object)
(704886, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 704886, dtype: object)
(704941, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 704941, dtype: object)
(726979, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 726979, dtype: object)
(727005, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 727005, dtype: object)
(727018, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 727018, dtype: object)
(727086, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 727086, dtype: object)
(727092, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 727092, dtype: object)
(735971, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 735971, dtype: object)
(736013, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 736013, dtype: object)
(748784, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 748784, dtype: object)
(780226, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 780226, dtype: object)
(803402, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 803402, dtype: object)
(829181, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 829181, dtype: object)
(839664, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 839664, dtype: object)
(839672, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 839672, dtype: object)
(839673, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 839673, dtype: object)

### การวนลูป แบบมองตารางแพนด้าส์(pandas dataframe) เป็น numpy array  (```.iloc```) อ่านว่าไอล็อก

In [32]:
for each_row in range(this_data.shape[0]):
    if (this_data.iloc[each_row,1] == 20) and (this_data.iloc[each_row,2] == 'ขอนแก่น'):  #each_row คือ ตัวเลข แล้วหลัง , คือลำดับคอลัมน์
        print(each_row) # อยากให้ print ลำดับ (9334)
        print(this_data.iloc[each_row,:])

9335
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 9335, dtype: object
31050
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 31050, dtype: object
34968
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 34968, dtype: object
36072
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 36072, dtype: object
39418
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 39418, dtype: object
42498
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 42498, dtype: object
44230
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 44230, dtype: object
45587
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 45587, dtype: object
48523
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 48523, dtype: object
53609
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 53609, dtype: object
57679
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 57679, dtype: object
59921
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 59921, dtype: object
59930
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 59930, dtype: object
62012
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 62012, dtype: object
194272
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 194272, dtype: object
256640
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 256640, dtype: object
267358
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 267358, dtype: object
267368
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 267368, dtype: object
304435
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 304435, dtype: object
312286
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 312286, dtype: object
321955
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 321955, dtype: object
321996
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 321996, dtype: object
340650
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 340650, dtype: object
340671
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 340671, dtype: object
349134
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 349134, dtype: object
368051
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 368051, dtype: object
377063
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 377063, dtype: object
377130
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 377130, dtype: object
388236
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 388236, dtype: object
401881
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 401881, dtype: object
410329
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 410329, dtype: object
410353
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 410353, dtype: object
410396
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 410396, dtype: object
420924
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 420924, dtype: object
433189
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 433189, dtype: object
433192
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 433192, dtype: object
433214
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 433214, dtype: object
433256
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 433256, dtype: object
433269
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 433269, dtype: object
433293
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 433293, dtype: object
446755
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 446755, dtype: object
452846
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 452846, dtype: object
452894
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 452894, dtype: object
460492
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 460492, dtype: object
460543
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 460543, dtype: object
460590
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 460590, dtype: object
466802
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 466802, dtype: object
466810
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 466810, dtype: object
466875
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 466875, dtype: object
475443
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 475443, dtype: object
475498
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 475498, dtype: object
475501
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 475501, dtype: object
481816
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 481816, dtype: object
481818
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 481818, dtype: object
481824
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 481824, dtype: object
496736
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 496736, dtype: object
496745
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 496745, dtype: object
496947
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 496947, dtype: object
505641
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 505641, dtype: object
520750
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 520750, dtype: object
535484
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 535484, dtype: object
553001
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 553001, dtype: object
553135
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 553135, dtype: object
553150
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 553150, dtype: object
555059
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 555059, dtype: object
560192
sex                      NaN
age                     20.0
province_of_onset    ขอนแก่น
Name: 560192, dtype: object
570704
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 570704, dtype: object
570785
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 570785, dtype: object
570796
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 570796, dtype: object
588443
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 588443, dtype: object
588445
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 588445, dtype: object
588447
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 588447, dtype: object
588468
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 588468, dtype: object
588525
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 588525, dtype: object
588532
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 588532, dtype: object
607922
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 607922, dtype: object
607942
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 607942, dtype: object
620478
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 620478, dtype: object
625602
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 625602, dtype: object
625628
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 625628, dtype: object
625651
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 625651, dtype: object
625717
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 625717, dtype: object
643471
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 643471, dtype: object
643473
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 643473, dtype: object
643528
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 643528, dtype: object
643600
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 643600, dtype: object
663475
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 663475, dtype: object
663521
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 663521, dtype: object
663570
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 663570, dtype: object
663591
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 663591, dtype: object
683820
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 683820, dtype: object
704781
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 704781, dtype: object
704805
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 704805, dtype: object
704886
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 704886, dtype: object
704941
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 704941, dtype: object
726979
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 726979, dtype: object
727005
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 727005, dtype: object
727018
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 727018, dtype: object
727086
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 727086, dtype: object
727092
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 727092, dtype: object
735971
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 735971, dtype: object
736013
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 736013, dtype: object
748784
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 748784, dtype: object
780226
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 780226, dtype: object
803402
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 803402, dtype: object
829181
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 829181, dtype: object
839664
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 839664, dtype: object
839672
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 839672, dtype: object
839673
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 839673, dtype: object

## Quiz ตัดตารางออกมาเฉพาะปี 2021 ```announce_date``` ในปี 2021

**Hint**
*   วนลูปหา index ของปี 2021
*   ตัดตารางมาเฉพาะ ปี 2021

In [ ]:
# จุดมุ่งหมมายของเราคือจะตัดมาเฉพราะปี 2021 โดยเราจะดูจาก announce_date
# ซึ่งตอนนี้มันเป็น format เดือน/วัน/ปี อยู่ซึ่งเราอยากได้แค่ปี2021 อย่างเดียว
# สิ่งที่เราทำคือวนลูปเข้าไปในแถวแต่ละแถวพอวนลูปเสร็จ
# แต่ทีนี้เราอยากใช้ค่า announce_date แต่หน้าตามันยังเป็น format อยู๋เราอยากได้แค่ปี เลยต้อง split('/') เพราะ format มันแบ่งด้วย /
# เราก็จะได้เป็น เดือนคือตำแหน่งที่ 0 , วันตำแหน่งที่, ปีตำแหน่งที่ 2 และเราต้องการแค่ก็ indict ไปที่ 2 แล้วกำหนดปีไปก็คือ == '2021'
# พอเราได้ปีมา 2021 มาแล้วเราก็มาสร้าง list ก็คือถ้าเจอปี 2021 จะใส่ว่า True แต่ถ้าไม่ใช่ให้ใส่ false
# สุดท้าย print ออกมาถ้ามีชื่อตารางก็จะออกมาทั้งตารางเลยที่มี 2021 แต่ถ้า Print แค่ TF ก็จะออกมาเป็น True and False
TF=list()
for each_row in data_covid.iterrows():
    if each_row[1]['announce_date'].split('/')[2] == '2021':
        TF.append(True)
    else:
        TF.append(False)

data_covid[TF].head()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
124,125,6/3/2021,5/3/2021,หญิง,55.0,ปี,Thailand,ปทุมธานี,Cluster ตลาดพรพัฒน์,ปทุมธานี,ธัญบุรี
6885,6886,1/1/2021,31/12/2020,หญิง,40.0,ปี,Thailand,กรุงเทพมหานคร,Cluster สมุทรสาคร,ปทุมธานี,คลองหลวง
6886,6887,1/1/2021,31/12/2020,หญิง,21.0,ปี,Thailand,ปทุมธานี,Cluster ระยอง,ปทุมธานี,คลองหลวง
6887,6888,1/1/2021,31/12/2020,หญิง,20.0,ปี,Thailand,นครปฐม,สถานบันเทิง,นครปฐม,สามพราน
6888,6889,1/1/2021,31/12/2020,หญิง,47.0,ปี,Thailand,สมุทรสาคร,Cluster สมุทรสาคร,นครปฐม,สามพราน

In [ ]:
TF[-10:]

[True, True, True, True, True, True, True, True, True, True]

# Function ตัวช่วยใน pandas

### ```.describe()``` คำนวณค่าทางสถิติของข้อมูลที่เป็นตัวเลข

In [ ]:
data_covid.describe()

                No.
count  839771.00000
mean   419886.00000
std    242421.15079
min         1.00000
25%    209943.50000
50%    419886.00000
75%    629828.50000
max    839771.00000

### ```.mean()``` คำนวณค่าเฉลี่ยของข้อมูลโดยไม่สนใจ missing

In [ ]:
data_covid['age'] = pd.to_numeric(data_covid['age'],errors='coerce')
data_covid[data_covid['sex']=='ชาย']['age'].mean()

np.float64(34.96292702130938)

### ```.isnull()```

In [ ]:
data_covid.isnull() # คือการเช็คค่าที่มีอยู่าเป็น True หรือ False หรือก็คือค่าว่างไหม

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,False,False,True,False,False,False,False,False,False,False,True
1,False,False,True,False,False,False,False,False,False,False,True
2,False,False,True,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,True
4,False,False,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
839766,False,False,False,False,False,False,True,False,False,False,True
839767,False,False,False,False,False,False,False,False,False,False,True
839768,False,False,False,False,False,False,False,False,False,False,True
839769,False,False,False,False,False,False,False,False,False,False,True
839770,False,False,False,False,False,False,False,False,False,False,True

In [ ]:
# .any คือการสรุปเอาค่าความจริงภายในแต่ละคอลัมน์มา and กัน ก็คือ True or True เป็น True
data_covid.isnull().any()

No.                      False
announce_date            False
Notified date             True
sex                       True
age                       True
Unit                      True
nationality               True
province_of_isolation     True
risk                      True
province_of_onset         True
district_of_onset         True
dtype: bool

In [ ]:
# .any คือการสรุปเอาค่าความจริงภายในแต่ละคอลัมน์มา and กัน ก็คือ True and True เป็น True
data_covid.isnull().all()

No.                      False
announce_date            False
Notified date            False
sex                      False
age                      False
Unit                     False
nationality              False
province_of_isolation    False
risk                     False
province_of_onset        False
district_of_onset        False
dtype: bool

In [ ]:
# การเช็คค่าว่า nall รึป่าว
data_covid.iloc[:1,0].isnull() # ใช้การตัดตารางเข้ามา

0    False
Name: No., dtype: bool

# next
*   .describe
*   .mean
*   HW วนลูป missing .isnull
*   ต่อตารางแกน X แกน y
*   .groupby
*   save table